version: "3.7"
services:
  vue:
    build:
      context: .
    image: alpine-vue:latest
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8081:8080"
    volumes:
      - ./frontend/workspace:/home
    networks:
      network_sql1:
        ipv4_address: 172.30.0.2

  python-api:
    build:
      context: .
    image: alpine-python:latest
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8080:80"
    volumes:
      - ./backend/workspace:/home
    depends_on:
      - postgres
    networks:
      network_sql2:
        ipv4_address: 172.31.0.2

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      network_sql2:
        ipv4_address: 172.31.0.3

networks:
  network_sql1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1


  network_sql2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1
