version: "3.7"
services:
  python-api:
    build:
      context: .
    image: alpine-python:latest
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8080:80"
    volumes:
      - ./backend/workspace:/home
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  vue:
    build:
      context: .
    image: alpine-vue:latest
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8081:8080"
    volumes:
      - ./frontend/workspace:/home
