version: "3.7"
services:
  vue:
    build:
      context: .
    image: alpine-vue:latest
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8081:8080"
    volumes:
      - ./frontend/workspace:/home
    networks:
      - network_sql1

  python-api:
    build:
      context: .
    image: alpine-python:latest
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8080:80"
    volumes:
      - ./backend/workspace:/home
    depends_on:
      - postgres
    networks:
      - network_sql2

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - network_sql2

networks:
  network_sql1:
    driver: bridge

  network_sql2:
    driver: bridge
